export interface LogisticsRow {
  id: string;
  isUrgent: boolean;
  date: string;
  clientInitials: string;
  clientName: string;
  clientColor: string;
  aluminio: 'pending' | 'in-progress' | 'ready' | 'none';
  vidrio: 'pending' | 'in-progress' | 'ready' | 'none';
  herrajes: 'pending' | 'in-progress' | 'ready' | 'none';
  estadoGeneral: 'pending' | 'in-progress' | 'ready' | 'none';
  type?: 'normal' | 'anticipada';
  totalDeliveries?: number;
  completedDeliveries?: number;
  assignedDriverId?: string;
  address?: string;
}

export const MOCK_LOGISTICS_DATA: LogisticsRow[] = [
  {
    id: "1015",
    isUrgent: true,
    date: "12 de marzo 2026",
    clientInitials: "EB",
    clientName: "Cliente 1",
    clientColor: "bg-[#FEEBC8] text-[#DD6B20]",
    aluminio: "pending",
    vidrio: "pending",
    herrajes: "pending",
    estadoGeneral: "pending",
    type: "normal",
  },
  {
    id: "1024",
    isUrgent: false,
    date: "24 de febrero 2026",
    clientInitials: "CS",
    clientName: "Cliente 2",
    clientColor: "bg-[#EBF8FF] text-[#3182CE]",
    aluminio: "ready",
    vidrio: "in-progress",
    herrajes: "none",
    estadoGeneral: "pending",
    type: "anticipada",
    totalDeliveries: 4,
    completedDeliveries: 3,
  },
  {
    id: "1023",
    isUrgent: true,
    date: "22 de febrero 2026",
    clientInitials: "MH",
    clientName: "Cliente 3",
    clientColor: "bg-[#C6F6D5] text-[#38A169]",
    aluminio: "ready",
    vidrio: "ready",
    herrajes: "ready",
    estadoGeneral: "ready",
    type: "normal",
  },
  {
    id: "1021",
    isUrgent: false,
    date: "22 de febrero 2026",
    clientInitials: "UD",
    clientName: "Cliente 4",
    clientColor: "bg-[#EBF4FF] text-[#4C51BF]",
    aluminio: "pending",
    vidrio: "none",
    herrajes: "pending",
    estadoGeneral: "pending",
    type: "anticipada",
    totalDeliveries: 3,
    completedDeliveries: 0,
  },
  {
    id: "1019",
    isUrgent: false,
    date: "21 de febrero 2026",
    clientInitials: "AR",
    clientName: "Cliente 5",
    clientColor: "bg-[#E9D8FD] text-[#805AD5]",
    aluminio: "in-progress",
    vidrio: "ready",
    herrajes: "none",
    estadoGeneral: "in-progress",
    type: "normal",
  },
  // Extra data for pagination testing
  {
    id: "1018",
    isUrgent: false,
    date: "20 de febrero 2026",
    clientInitials: "TS",
    clientName: "Cliente 6",
    clientColor: "bg-[#FED7D7] text-[#C53030]",
    aluminio: "none",
    vidrio: "ready",
    herrajes: "ready",
    estadoGeneral: "ready",
    type: "normal",
  },
  {
    id: "1017",
    isUrgent: false,
    date: "11 de marzo 2026",
    clientInitials: "LP",
    clientName: "Cliente 7",
    clientColor: "bg-[#C6F6D5] text-[#38A169]",
    aluminio: "pending",
    vidrio: "in-progress",
    herrajes: "ready",
    estadoGeneral: "in-progress",
    type: "anticipada",
    totalDeliveries: 2,
    completedDeliveries: 0,
  },
  {
    id: "1025",
    isUrgent: true,
    date: "10 de marzo 2026",
    clientInitials: "JR",
    clientName: "Cliente 8",
    clientColor: "bg-[#FEEBC8] text-[#DD6B20]",
    aluminio: "none",
    vidrio: "pending",
    herrajes: "none",
    estadoGeneral: "pending",
  },
  {
    id: "1026",
    isUrgent: false,
    date: "25 de febrero 2026",
    clientInitials: "MA",
    clientName: "Cliente 9",
    clientColor: "bg-[#EBF8FF] text-[#3182CE]",
    aluminio: "in-progress",
    vidrio: "in-progress",
    herrajes: "ready",
    estadoGeneral: "in-progress",
  },
  {
    id: "1027",
    isUrgent: false,
    date: "26 de febrero 2026",
    clientInitials: "PL",
    clientName: "Cliente 10",
    clientColor: "bg-[#C6F6D5] text-[#38A169]",
    aluminio: "none",
    vidrio: "none",
    herrajes: "ready",
    estadoGeneral: "ready",
    address: "Calle Aramberri 456, Centro, Monterrey",
  },
  {
    id: "1028",
    isUrgent: false,
    date: "09 de marzo 2026",
    clientInitials: "RS",
    clientName: "Cliente 11",
    clientColor: "bg-[#EBF4FF] text-[#4C51BF]",
    aluminio: "none",
    vidrio: "pending",
    herrajes: "pending",
    estadoGeneral: "pending",
  },
  {
    id: "1029",
    isUrgent: false,
    date: "27 de febrero 2026",
    clientInitials: "TK",
    clientName: "Cliente 12",
    clientColor: "bg-[#E9D8FD] text-[#805AD5]",
    aluminio: "in-progress",
    vidrio: "none",
    herrajes: "none",
    estadoGeneral: "in-progress",
  },
  {
    id: "1030",
    isUrgent: false,
    date: "28 de febrero 2026",
    clientInitials: "NV",
    clientName: "Cliente 13",
    clientColor: "bg-[#FED7D7] text-[#C53030]",
    aluminio: "ready",
    vidrio: "ready",
    herrajes: "ready",
    estadoGeneral: "ready",
    type: "anticipada",
    totalDeliveries: 3,
    completedDeliveries: 2,
    address: "Blvd. Puerta del Sol 789, San Pedro",
  },
  {
    id: "1031",
    isUrgent: false,
    date: "08 de marzo 2026",
    clientInitials: "KM",
    clientName: "Cliente 14",
    clientColor: "bg-[#EBF8FF] text-[#3182CE]",
    aluminio: "pending",
    vidrio: "none",
    herrajes: "pending",
    estadoGeneral: "pending",
  },
  {
    id: "1032",
    isUrgent: false,
    date: "01 de marzo 2026",
    clientInitials: "LF",
    clientName: "Cliente 15",
    clientColor: "bg-[#C6F6D5] text-[#38A169]",
    aluminio: "ready",
    vidrio: "ready",
    herrajes: "ready",
    estadoGeneral: "ready",
  },
  {
    id: "1033",
    isUrgent: false,
    date: "01 de marzo 2026",
    clientInitials: "SD",
    clientName: "Cliente 16",
    clientColor: "bg-[#FEEBC8] text-[#DD6B20]",
    aluminio: "in-progress",
    vidrio: "in-progress",
    herrajes: "in-progress",
    estadoGeneral: "in-progress",
  },
  {
    id: "1034",
    isUrgent: false,
    date: "07 de marzo 2026",
    clientInitials: "BP",
    clientName: "Cliente 17",
    clientColor: "bg-[#E9D8FD] text-[#805AD5]",
    aluminio: "pending",
    vidrio: "ready",
    herrajes: "pending",
    estadoGeneral: "pending",
  },
  {
    id: "1035",
    isUrgent: false,
    date: "02 de marzo 2026",
    clientInitials: "OM",
    clientName: "Cliente 18",
    clientColor: "bg-[#EBF4FF] text-[#4C51BF]",
    aluminio: "ready",
    vidrio: "ready",
    herrajes: "ready",
    estadoGeneral: "ready",
  },
  {
    id: "1036",
    isUrgent: false,
    date: "03 de marzo 2026",
    clientInitials: "HT",
    clientName: "Cliente 19",
    clientColor: "bg-[#FED7D7] text-[#C53030]",
    aluminio: "in-progress",
    vidrio: "ready",
    herrajes: "ready",
    estadoGeneral: "in-progress",
  },
  {
    id: "1037",
    isUrgent: false,
    date: "06 de marzo 2026",
    clientInitials: "YU",
    clientName: "Cliente 20",
    clientColor: "bg-[#C6F6D5] text-[#38A169]",
    aluminio: "pending",
    vidrio: "pending",
    herrajes: "pending",
    estadoGeneral: "pending",
  },
  {
    id: "1038",
    isUrgent: false,
    date: "04 de marzo 2026",
    clientInitials: "WQ",
    clientName: "Cliente 21",
    clientColor: "bg-[#EBF8FF] text-[#3182CE]",
    aluminio: "ready",
    vidrio: "ready",
    herrajes: "ready",
    estadoGeneral: "ready",
  },
  {
    id: "1039",
    isUrgent: false,
    date: "05 de marzo 2026",
    clientInitials: "XC",
    clientName: "Cliente 22",
    clientColor: "bg-[#FEEBC8] text-[#DD6B20]",
    aluminio: "in-progress",
    vidrio: "pending",
    herrajes: "ready",
    estadoGeneral: "in-progress",
  },
  {
    id: "1040",
    isUrgent: false,
    date: "05 de marzo 2026",
    clientInitials: "ZA",
    clientName: "Cliente 23",
    clientColor: "bg-[#E9D8FD] text-[#805AD5]",
    aluminio: "pending",
    vidrio: "pending",
    herrajes: "pending",
    estadoGeneral: "pending",
  },
  {
    id: "1041",
    isUrgent: false,
    date: "06 de marzo 2026",
    clientInitials: "MN",
    clientName: "Cliente 24",
    clientColor: "bg-[#C6F6D5] text-[#38A169]",
    aluminio: "ready",
    vidrio: "ready",
    herrajes: "ready",
    estadoGeneral: "ready",
  },
  {
    id: "1042",
    isUrgent: false,
    date: "07 de marzo 2026",
    clientInitials: "LK",
    clientName: "Cliente 25",
    clientColor: "bg-[#EBF4FF] text-[#4C51BF]",
    aluminio: "in-progress",
    vidrio: "in-progress",
    herrajes: "in-progress",
    estadoGeneral: "in-progress",
  },
  {
    id: "1043",
    isUrgent: false,
    date: "08 de marzo 2026",
    clientInitials: "PO",
    clientName: "Cliente 26",
    clientColor: "bg-[#FED7D7] text-[#C53030]",
    aluminio: "pending",
    vidrio: "ready",
    herrajes: "ready",
    estadoGeneral: "pending",
  },
  {
    id: "1044",
    isUrgent: false,
    date: "08 de marzo 2026",
    clientInitials: "DS",
    clientName: "Cliente 27",
    clientColor: "bg-[#EBF8FF] text-[#3182CE]",
    aluminio: "ready",
    vidrio: "ready",
    herrajes: "ready",
    estadoGeneral: "ready",
  },
];

